title: Anton Jørgensen
logo: /assets/img/logo.png
email: anton2410@gmail.com
description: Test
show_downloads: false
google_analytics: UA-108144808-1
theme: jekyll-theme-minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
