# Sidebar info
title: Anton Jørgensen
logo: https://avatars.githubusercontent.com/u/33018671?v=4
email: anton2410@gmail.com
description: Aspiring Data Science Engineer
github: https://github.com/AntonJorg/
blog: https://blog.antonjorg.com
linkedin: https://www.linkedin.com/in/anton-jorg/
show_downloads: false

# Appearance
favicon: true
remote_theme: BDHU/minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
